global:
  resolve_timeout: 1m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
    - api_url: 'COLE_AQUI_O_Webhook_URL_DO_SLACK'
      channel: '#prometheus-alerts'
      send_resolved: true

