version: '3'
services:
  web-server:
    image: "lab4linux/app-4linux:latest"
    restart: unless-stopped
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: 3306
      DB_USER: php
      DB_PASS: 4linux
      DB_NAME: php
    ports:
     - "80:80"
    volumes:
      - "/570/config/php.ini:/etc/php/8.1/apache2/php.ini"
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
