version: '3'
services:
  web-server:
    image: "lab4linux/4linux-app"
    environment:
      DB_HOST: db-server.4labs.example
      DB_PORT: 3306
      DB_USER: php
      DB_PASS: 4linux
      DB_NAME: php
    ports:
      - "80:8080"
    volumes:
      - "/570/config/php.ini:/etc/php7/php.ini"
