version: '3'
services:
  web-server:
    image: "lab4linux/app-4linux:latest"
    restart: unless-stopped
    environment:
      DB_HOST: "db-server"
      DB_PORT: 3306
      DB_USER: php
      DB_PASS: 4linux
      DB_NAME: php
    ports:
     - "80:80"
    volumes:
      - "/570/config/php.ini:/usr/local/etc/php/php.ini"
      - "/570/config/server-status.conf:/etc/apache2/conf-enabled/server-status.conf"       
