version: '3'
services:
  memcached-server:
    image: "memcached"
    restart: unless-stopped
    ports:
      - "11211:11211"
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes: 
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
  memcached-exporter:
    image: prom/memcached-exporter
    container_name: memcached-exporter
    restart: unless-stopped
    ports:
      - "9150:9150"
    command:
      - --memcached.address=IP:11211
